// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7WXMzqT6kj_PgFC800zLgLsjSjXQpio',
    appId: '1:891640062852:web:3fb609820d853d3740b3d1',
    messagingSenderId: '891640062852',
    projectId: 'internal-system-flutter',
    authDomain: 'internal-system-flutter.firebaseapp.com',
    databaseURL: 'https://internal-system-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'internal-system-flutter.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE8KFKXcg1ATVd6l-G9P7BHKrfXt--QZ8',
    appId: '1:891640062852:ios:2eeae4e600ed39b940b3d1',
    messagingSenderId: '891640062852',
    projectId: 'internal-system-flutter',
    databaseURL: 'https://internal-system-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'internal-system-flutter.firebasestorage.app',
    iosBundleId: 'com.example.internalsystem',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE8KFKXcg1ATVd6l-G9P7BHKrfXt--QZ8',
    appId: '1:891640062852:ios:2eeae4e600ed39b940b3d1',
    messagingSenderId: '891640062852',
    projectId: 'internal-system-flutter',
    databaseURL: 'https://internal-system-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'internal-system-flutter.firebasestorage.app',
    iosBundleId: 'com.example.internalsystem',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfc2Oz8JxrflhlwX3Txwahuel0bxSD4s',
    appId: '1:891640062852:android:6787155fc3afe7a440b3d1',
    messagingSenderId: '891640062852',
    projectId: 'internal-system-flutter',
    databaseURL: 'https://internal-system-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'internal-system-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn7WXMzqT6kj_PgFC800zLgLsjSjXQpio',
    appId: '1:891640062852:web:b9215477807fbb3740b3d1',
    messagingSenderId: '891640062852',
    projectId: 'internal-system-flutter',
    authDomain: 'internal-system-flutter.firebaseapp.com',
    databaseURL: 'https://internal-system-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'internal-system-flutter.firebasestorage.app',
  );

}